(define byeoru-on-key '("<Shift> " "hangul"))
(define byeoru-on-key? (make-key-predicate '("<Shift> " "hangul")))
(define byeoru-latin-key '("<Shift> " "hangul"))
(define byeoru-latin-key? (make-key-predicate '("<Shift> " "hangul")))
(define byeoru-conversion-key '("hangul-hanja"))
(define byeoru-conversion-key? (make-key-predicate '("hangul-hanja")))
(define byeoru-commit-key '("return"))
(define byeoru-commit-key? (make-key-predicate '("return")))
(define byeoru-cancel-key '("escape"))
(define byeoru-cancel-key? (make-key-predicate '("escape")))
